#!/bin/bash

CURRENT_DIR=$(pwd)

# Function to handle tmux session creation for zsh
tmux_custom_zsh() {
    SESSION_NAME=${1:-MyZsh}  # Use provided name or default to "MyZsh"

    ZDOTDIR=$CURRENT_DIR/my_files
    tmux -f "$ZDOTDIR/.tmux.conf" new-session -d -s "$SESSION_NAME" \
        "ZDOTDIR='$ZDOTDIR' VIMINIT='source $ZDOTDIR/.vimrc' zsh"
    
    # Attach to session
    tmux attach-session -t "$SESSION_NAME"
}

# Function to handle tmux session creation for bash
tmux_custom_bash() {
    SESSION_NAME=${1:-MyBash}  # Use provided name or default to "MyBash"
    
    # Start new session with custom bashrc
    tmux -f "$CURRENT_DIR/my_files/.tmux.conf" new-session -d -s "$SESSION_NAME" \
        "VIMINIT='source $CURRENT_DIR/my_files/.vimrc' bash --rcfile '$CURRENT_DIR/my_files/.bashrc'"
    
    
    # Attach to session
    tmux attach-session -t "$SESSION_NAME"
}

# # Run the function

if [[ "$SHELL" == *"zsh"* ]]; then
    tmux_custom_zsh "$@"
elif [[ "$SHELL" == *"bash"* ]]; then
    tmux_custom_bash "$@"
else
    echo "Unsupported shell: $SHELL"
fi