#!/bin/sh

CURRENT_DIR=$(pwd)
DOT_DIR=$CURRENT_DIR/QuickShellMyFiles

# Function to handle tmux session creation for zsh
tmux_custom_zsh() {
    SESSION_NAME=${1:-MyZsh}  # Use provided name or default to "MyZsh"

    tmux new-session -d -s "$SESSION_NAME" \
        "ZDOTDIR='$DOT_DIR' VIMINIT='source $DOT_DIR/.vimrc' zsh"

    tmux source-file "$DOT_DIR/.tmux.conf"
    tmux set-option -t "$SESSION_NAME" default-command "ZDOTDIR='$DOT_DIR' VIMINIT='source $DOT_DIR/.vimrc' zsh"
}

# Function to handle tmux session creation for bash
tmux_custom_bash() {
    SESSION_NAME=${1:-MyBash}  # Use provided name or default to "MyBash"
    
    tmux new-session -d -s "$SESSION_NAME" \
        "VIMINIT='source $DOT_DIR/.vimrc' bash --rcfile '$DOT_DIR/.bashrc'"
    
    tmux source-file "$DOT_DIR/.tmux.conf"
    tmux set-option -t "$SESSION_NAME" default-command "TMUX_CONF='$DOT_DIR/.tmux.conf' VIMINIT='source $DOT_DIR/.vimrc' bash --rcfile '$DOT_DIR/.bashrc'"
}

# Function to handle tmux session creation for csh
tmux_custom_csh() {
    SESSION_NAME=${1:-MyCsh}  # Use provided name or default to "MyCsh"
    
    tmux new-session -d -s "$SESSION_NAME" \
        "setenv VIMINIT 'source $DOT_DIR/.vimrc'; csh -f -c 'source $DOT_DIR/.cshrc'"
    
    tmux source-file "$DOT_DIR/.tmux.conf"
    tmux set-option -t "$SESSION_NAME" default-command "setenv VIMINIT 'source $DOT_DIR/.vimrc'; setenv TMUX_CONF '$DOT_DIR/.tmux.conf'; csh -f -c 'source $DOT_DIR/.cshrc'"
}


# Run the function
case "$SHELL" in
    *zsh*)
    tmux_custom_zsh "$@"
        ;;
    *bash*)
    tmux_custom_bash "$@"
        ;;
    *csh*)
    tmux_custom_csh "$@"
        ;;
    *)
        echo "Unsupported shell: $SHELL"
        ;;
esac
